In [22]:
import scipy
from spafe.features.gfcc import gfcc
import os
import glob
import joblib
import numpy as np
from tqdm import tqdm
import librosa
from librosa import display
import wavio

import scipy.io.wavfile
import spafe.utils.vis as vis
from spafe.features.gfcc import gfcc

In [73]:
def extract(audio_file):
    name=os.path.basename(audio_file)
    name=os.path.splitext(name)[0]
    label = int(name[7:8]) - 1
    
    return label, audio_file
    
    
def return_feats(dir_name):
    X_ = []
    y_ = []
    err_cnt = 0
    err_list = []
    exeption_list = []
    
    #progression bar 
    file_count = len(dir_name)
    bar = tqdm(desc="proccessing files", total=file_count)
    tot = 0
    
    for file in dir_name:
        bar.update(1)
        tot += 1
        label, audio_file = extract(file)
        
        try:
            signal, sample_rate = librosa.load(audio_file, res_type='kaiser_fast')
            tonnetz = np.mean(librosa.feature.tonnetz(y=signal, sr=sample_rate).T,axis=0) 
            
            X_.append(tonnetz)
            y_.append(label)
            
        except Exception as e:
            err_cnt += 1
            err_list.append(audio_file)
            exeption_list.append(str(e))
            print("{}.error at:".format(err_cnt), audio_file)
            
        
    return X_, y_, err_cnt, err_list, exeption_list

In [74]:
dir_name = glob.glob("toronto_ds/conc_data/*.wav")

X, y, _, _, _ = return_feats(dir_name)
X_name, y_name = 'tonnetz_feats/X.joblib', 'tonnetz_feats/y.joblib'

joblib.dump(np.float64(X), X_name)
joblib.dump(y, y_name)




proccessing files:   0%|          | 0/5252 [00:00<?, ?it/s]


proccessing files:   0%|          | 2/5252 [00:00<05:24, 16.17it/s]


proccessing files:   0%|          | 4/5252 [00:00<07:23, 11.83it/s]


proccessing files:   0%|          | 5/5252 [00:00<07:54, 11.05it/s]


proccessing files:   0%|          | 6/5252 [00:00<10:17,  8.49it/s]


proccessing files:   0%|          | 7/5252 [00:00<12:57,  6.75it/s]


proccessing files:   0%|          | 8/5252 [00:01<11:58,  7.30it/s]


proccessing files:   0%|          | 9/5252 [00:01<11:08,  7.84it/s]


proccessing files:   0%|          | 10/5252 [00:01<12:34,  6.95it/s]


proccessing files:   0%|          | 11/5252 [00:01<11:47,  7.41it/s]


proccessing files:   0%|          | 12/5252 [00:01<14:01,  6.23it/s]


proccessing files:   0%|          | 13/5252 [00:01<12:45,  6.85it/s]


proccessing files:   0%|          | 14/5252 [00:01<12:06,  7.21it/s]


proccessing files:   0%|          | 15/5252 [00:02<11:56,  7.31it/s]


proccessing files: 

proccessing files:   4%|▍         | 216/5252 [00:33<11:23,  7.37it/s]


proccessing files:   4%|▍         | 217/5252 [00:34<11:10,  7.51it/s]


proccessing files:   4%|▍         | 218/5252 [00:34<10:37,  7.90it/s]


proccessing files:   4%|▍         | 219/5252 [00:34<10:19,  8.13it/s]


proccessing files:   4%|▍         | 220/5252 [00:34<11:50,  7.09it/s]


proccessing files:   4%|▍         | 221/5252 [00:34<10:58,  7.64it/s]


proccessing files:   4%|▍         | 222/5252 [00:34<10:17,  8.15it/s]


proccessing files:   4%|▍         | 223/5252 [00:34<10:17,  8.14it/s]


proccessing files:   4%|▍         | 224/5252 [00:34<10:15,  8.17it/s]


proccessing files:   4%|▍         | 225/5252 [00:35<09:49,  8.53it/s]


proccessing files:   4%|▍         | 226/5252 [00:35<09:47,  8.55it/s]


proccessing files:   4%|▍         | 227/5252 [00:35<11:08,  7.51it/s]


proccessing files:   4%|▍         | 228/5252 [00:35<13:19,  6.28it/s]


proccessing files:   4%|▍         | 229/5252 [00:35<11:50,  7.07

proccessing files:   8%|▊         | 425/5252 [01:04<13:24,  6.00it/s]


proccessing files:   8%|▊         | 426/5252 [01:04<15:04,  5.33it/s]


proccessing files:   8%|▊         | 427/5252 [01:05<13:23,  6.00it/s]


proccessing files:   8%|▊         | 428/5252 [01:05<12:33,  6.40it/s]


proccessing files:   8%|▊         | 429/5252 [01:05<11:49,  6.80it/s]


proccessing files:   8%|▊         | 430/5252 [01:05<13:14,  6.07it/s]


proccessing files:   8%|▊         | 431/5252 [01:05<12:05,  6.65it/s]


proccessing files:   8%|▊         | 432/5252 [01:05<13:04,  6.14it/s]


proccessing files:   8%|▊         | 433/5252 [01:06<14:52,  5.40it/s]


proccessing files:   8%|▊         | 434/5252 [01:06<12:58,  6.19it/s]


proccessing files:   8%|▊         | 435/5252 [01:06<11:58,  6.71it/s]


proccessing files:   8%|▊         | 436/5252 [01:06<14:02,  5.72it/s]


proccessing files:   8%|▊         | 437/5252 [01:06<14:55,  5.38it/s]


proccessing files:   8%|▊         | 438/5252 [01:06<15:08,  5.30

proccessing files:  12%|█▏        | 641/5252 [01:38<10:17,  7.46it/s]


proccessing files:  12%|█▏        | 642/5252 [01:38<11:08,  6.89it/s]


proccessing files:  12%|█▏        | 643/5252 [01:39<12:34,  6.11it/s]


proccessing files:  12%|█▏        | 644/5252 [01:39<11:16,  6.81it/s]


proccessing files:  12%|█▏        | 645/5252 [01:39<12:09,  6.31it/s]


proccessing files:  12%|█▏        | 646/5252 [01:39<11:09,  6.88it/s]


proccessing files:  12%|█▏        | 647/5252 [01:39<12:47,  6.00it/s]


proccessing files:  12%|█▏        | 648/5252 [01:39<11:47,  6.51it/s]


proccessing files:  12%|█▏        | 649/5252 [01:39<10:37,  7.21it/s]


proccessing files:  12%|█▏        | 650/5252 [01:40<12:11,  6.29it/s]


proccessing files:  12%|█▏        | 651/5252 [01:40<13:15,  5.78it/s]


proccessing files:  12%|█▏        | 652/5252 [01:40<11:34,  6.62it/s]


proccessing files:  12%|█▏        | 653/5252 [01:40<13:14,  5.79it/s]


proccessing files:  12%|█▏        | 654/5252 [01:40<11:38,  6.58

proccessing files:  16%|█▋        | 857/5252 [02:12<09:55,  7.38it/s]


proccessing files:  16%|█▋        | 858/5252 [02:12<09:38,  7.59it/s]


proccessing files:  16%|█▋        | 859/5252 [02:12<09:19,  7.85it/s]


proccessing files:  16%|█▋        | 860/5252 [02:12<09:01,  8.12it/s]


proccessing files:  16%|█▋        | 861/5252 [02:12<08:47,  8.32it/s]


proccessing files:  16%|█▋        | 862/5252 [02:13<10:17,  7.11it/s]


proccessing files:  16%|█▋        | 863/5252 [02:13<11:33,  6.33it/s]


proccessing files:  16%|█▋        | 865/5252 [02:13<11:01,  6.64it/s]


proccessing files:  16%|█▋        | 866/5252 [02:13<11:51,  6.16it/s]


proccessing files:  17%|█▋        | 868/5252 [02:13<11:23,  6.42it/s]


proccessing files:  17%|█▋        | 869/5252 [02:14<11:58,  6.10it/s]


proccessing files:  17%|█▋        | 871/5252 [02:14<11:39,  6.26it/s]


proccessing files:  17%|█▋        | 872/5252 [02:14<10:38,  6.87it/s]


proccessing files:  17%|█▋        | 873/5252 [02:14<12:17,  5.94

proccessing files:  20%|██        | 1071/5252 [02:44<09:44,  7.15it/s]


proccessing files:  20%|██        | 1072/5252 [02:44<11:16,  6.18it/s]


proccessing files:  20%|██        | 1073/5252 [02:44<11:35,  6.01it/s]


proccessing files:  20%|██        | 1074/5252 [02:45<10:19,  6.75it/s]


proccessing files:  20%|██        | 1075/5252 [02:45<09:38,  7.21it/s]


proccessing files:  20%|██        | 1076/5252 [02:45<10:12,  6.81it/s]


proccessing files:  21%|██        | 1077/5252 [02:45<09:39,  7.21it/s]


proccessing files:  21%|██        | 1078/5252 [02:45<09:14,  7.53it/s]


proccessing files:  21%|██        | 1079/5252 [02:45<08:40,  8.02it/s]


proccessing files:  21%|██        | 1080/5252 [02:45<10:13,  6.80it/s]


proccessing files:  21%|██        | 1081/5252 [02:46<12:07,  5.73it/s]


proccessing files:  21%|██        | 1082/5252 [02:46<11:00,  6.31it/s]


proccessing files:  21%|██        | 1083/5252 [02:46<12:14,  5.67it/s]


proccessing files:  21%|██        | 1084/5252 [02:4

proccessing files:  24%|██▍       | 1278/5252 [03:18<10:46,  6.15it/s]


proccessing files:  24%|██▍       | 1279/5252 [03:18<11:26,  5.79it/s]


proccessing files:  24%|██▍       | 1280/5252 [03:18<10:06,  6.55it/s]


proccessing files:  24%|██▍       | 1281/5252 [03:18<09:12,  7.19it/s]


proccessing files:  24%|██▍       | 1282/5252 [03:18<10:47,  6.13it/s]


proccessing files:  24%|██▍       | 1283/5252 [03:18<09:51,  6.71it/s]


proccessing files:  24%|██▍       | 1284/5252 [03:19<11:26,  5.78it/s]


proccessing files:  24%|██▍       | 1285/5252 [03:19<12:28,  5.30it/s]


proccessing files:  24%|██▍       | 1286/5252 [03:19<13:02,  5.07it/s]


proccessing files:  25%|██▍       | 1287/5252 [03:19<11:21,  5.82it/s]


proccessing files:  25%|██▍       | 1288/5252 [03:19<12:18,  5.37it/s]


proccessing files:  25%|██▍       | 1289/5252 [03:19<10:44,  6.15it/s]


proccessing files:  25%|██▍       | 1290/5252 [03:20<09:45,  6.76it/s]


proccessing files:  25%|██▍       | 1291/5252 [03:2

proccessing files:  28%|██▊       | 1478/5252 [03:50<10:48,  5.82it/s]


proccessing files:  28%|██▊       | 1479/5252 [03:50<11:09,  5.64it/s]


proccessing files:  28%|██▊       | 1480/5252 [03:51<11:46,  5.34it/s]


proccessing files:  28%|██▊       | 1481/5252 [03:51<12:47,  4.91it/s]


proccessing files:  28%|██▊       | 1482/5252 [03:51<12:27,  5.04it/s]


proccessing files:  28%|██▊       | 1483/5252 [03:51<12:49,  4.90it/s]


proccessing files:  28%|██▊       | 1484/5252 [03:51<11:05,  5.66it/s]


proccessing files:  28%|██▊       | 1485/5252 [03:52<09:46,  6.43it/s]


proccessing files:  28%|██▊       | 1486/5252 [03:52<10:20,  6.07it/s]


proccessing files:  28%|██▊       | 1487/5252 [03:52<09:14,  6.79it/s]


proccessing files:  28%|██▊       | 1488/5252 [03:52<09:58,  6.29it/s]


proccessing files:  28%|██▊       | 1489/5252 [03:52<10:32,  5.95it/s]


proccessing files:  28%|██▊       | 1490/5252 [03:52<11:38,  5.39it/s]


proccessing files:  28%|██▊       | 1491/5252 [03:5

proccessing files:  32%|███▏      | 1683/5252 [04:22<07:00,  8.49it/s]


proccessing files:  32%|███▏      | 1684/5252 [04:22<08:02,  7.40it/s]


proccessing files:  32%|███▏      | 1685/5252 [04:22<09:46,  6.08it/s]


proccessing files:  32%|███▏      | 1686/5252 [04:23<10:25,  5.70it/s]


proccessing files:  32%|███▏      | 1687/5252 [04:23<10:14,  5.80it/s]


proccessing files:  32%|███▏      | 1688/5252 [04:23<10:22,  5.72it/s]


proccessing files:  32%|███▏      | 1689/5252 [04:23<10:43,  5.54it/s]


proccessing files:  32%|███▏      | 1690/5252 [04:23<10:22,  5.72it/s]


proccessing files:  32%|███▏      | 1691/5252 [04:23<09:21,  6.34it/s]


proccessing files:  32%|███▏      | 1692/5252 [04:24<10:37,  5.58it/s]


proccessing files:  32%|███▏      | 1693/5252 [04:24<10:21,  5.72it/s]


proccessing files:  32%|███▏      | 1694/5252 [04:24<09:27,  6.27it/s]


proccessing files:  32%|███▏      | 1695/5252 [04:24<08:30,  6.96it/s]


proccessing files:  32%|███▏      | 1696/5252 [04:2

proccessing files:  36%|███▌      | 1891/5252 [04:54<08:38,  6.48it/s]


proccessing files:  36%|███▌      | 1892/5252 [04:54<10:24,  5.38it/s]


proccessing files:  36%|███▌      | 1893/5252 [04:54<09:07,  6.13it/s]


proccessing files:  36%|███▌      | 1894/5252 [04:55<10:07,  5.53it/s]


proccessing files:  36%|███▌      | 1895/5252 [04:55<08:56,  6.25it/s]


proccessing files:  36%|███▌      | 1896/5252 [04:55<10:15,  5.46it/s]


proccessing files:  36%|███▌      | 1897/5252 [04:55<08:51,  6.31it/s]


proccessing files:  36%|███▌      | 1898/5252 [04:55<08:05,  6.91it/s]


proccessing files:  36%|███▌      | 1899/5252 [04:55<09:05,  6.15it/s]


proccessing files:  36%|███▌      | 1900/5252 [04:55<08:02,  6.94it/s]


proccessing files:  36%|███▌      | 1901/5252 [04:56<07:49,  7.14it/s]


proccessing files:  36%|███▌      | 1902/5252 [04:56<08:27,  6.60it/s]


proccessing files:  36%|███▋      | 1904/5252 [04:56<08:34,  6.51it/s]


proccessing files:  36%|███▋      | 1905/5252 [04:5

proccessing files:  40%|███▉      | 2095/5252 [05:25<06:49,  7.71it/s]


proccessing files:  40%|███▉      | 2096/5252 [05:25<06:26,  8.17it/s]


proccessing files:  40%|███▉      | 2097/5252 [05:25<07:44,  6.79it/s]


proccessing files:  40%|███▉      | 2098/5252 [05:26<07:02,  7.47it/s]


proccessing files:  40%|███▉      | 2099/5252 [05:26<06:40,  7.87it/s]


proccessing files:  40%|███▉      | 2100/5252 [05:26<07:30,  7.00it/s]


proccessing files:  40%|████      | 2101/5252 [05:26<08:43,  6.01it/s]


proccessing files:  40%|████      | 2102/5252 [05:26<08:03,  6.52it/s]


proccessing files:  40%|████      | 2103/5252 [05:26<08:25,  6.23it/s]


proccessing files:  40%|████      | 2104/5252 [05:27<08:49,  5.94it/s]


proccessing files:  40%|████      | 2105/5252 [05:27<09:14,  5.67it/s]


proccessing files:  40%|████      | 2106/5252 [05:27<08:18,  6.31it/s]


proccessing files:  40%|████      | 2107/5252 [05:27<09:33,  5.48it/s]


proccessing files:  40%|████      | 2108/5252 [05:2

proccessing files:  44%|████▎     | 2297/5252 [05:57<09:12,  5.35it/s]


proccessing files:  44%|████▍     | 2298/5252 [05:58<08:21,  5.89it/s]


proccessing files:  44%|████▍     | 2299/5252 [05:58<08:30,  5.78it/s]


proccessing files:  44%|████▍     | 2300/5252 [05:58<07:37,  6.45it/s]


proccessing files:  44%|████▍     | 2301/5252 [05:58<08:52,  5.54it/s]


proccessing files:  44%|████▍     | 2302/5252 [05:58<07:49,  6.29it/s]


proccessing files:  44%|████▍     | 2303/5252 [05:58<07:15,  6.78it/s]


proccessing files:  44%|████▍     | 2304/5252 [05:58<06:34,  7.48it/s]


proccessing files:  44%|████▍     | 2305/5252 [05:59<06:12,  7.90it/s]


proccessing files:  44%|████▍     | 2306/5252 [05:59<06:01,  8.14it/s]


proccessing files:  44%|████▍     | 2307/5252 [05:59<06:08,  8.00it/s]


proccessing files:  44%|████▍     | 2308/5252 [05:59<06:09,  7.97it/s]


proccessing files:  44%|████▍     | 2309/5252 [05:59<06:00,  8.16it/s]


proccessing files:  44%|████▍     | 2310/5252 [05:5

proccessing files:  48%|████▊     | 2507/5252 [06:29<07:14,  6.32it/s]


proccessing files:  48%|████▊     | 2508/5252 [06:30<08:09,  5.60it/s]


proccessing files:  48%|████▊     | 2509/5252 [06:30<08:46,  5.21it/s]


proccessing files:  48%|████▊     | 2510/5252 [06:30<07:39,  5.97it/s]


proccessing files:  48%|████▊     | 2511/5252 [06:30<06:47,  6.72it/s]


proccessing files:  48%|████▊     | 2513/5252 [06:30<06:51,  6.65it/s]


proccessing files:  48%|████▊     | 2514/5252 [06:31<07:44,  5.89it/s]


proccessing files:  48%|████▊     | 2516/5252 [06:31<06:48,  6.69it/s]


proccessing files:  48%|████▊     | 2517/5252 [06:31<06:09,  7.39it/s]


proccessing files:  48%|████▊     | 2518/5252 [06:31<05:52,  7.75it/s]


proccessing files:  48%|████▊     | 2519/5252 [06:31<06:56,  6.57it/s]


proccessing files:  48%|████▊     | 2520/5252 [06:31<07:16,  6.26it/s]


proccessing files:  48%|████▊     | 2521/5252 [06:31<07:21,  6.19it/s]


proccessing files:  48%|████▊     | 2522/5252 [06:3

proccessing files:  52%|█████▏    | 2720/5252 [07:01<06:01,  7.01it/s]


proccessing files:  52%|█████▏    | 2721/5252 [07:01<06:20,  6.65it/s]


proccessing files:  52%|█████▏    | 2722/5252 [07:01<05:49,  7.25it/s]


proccessing files:  52%|█████▏    | 2723/5252 [07:02<05:23,  7.83it/s]


proccessing files:  52%|█████▏    | 2724/5252 [07:02<06:20,  6.64it/s]


proccessing files:  52%|█████▏    | 2725/5252 [07:02<05:48,  7.25it/s]


proccessing files:  52%|█████▏    | 2726/5252 [07:02<06:54,  6.09it/s]


proccessing files:  52%|█████▏    | 2727/5252 [07:02<07:57,  5.29it/s]


proccessing files:  52%|█████▏    | 2728/5252 [07:03<08:24,  5.01it/s]


proccessing files:  52%|█████▏    | 2729/5252 [07:03<07:19,  5.74it/s]


proccessing files:  52%|█████▏    | 2730/5252 [07:03<06:31,  6.44it/s]


proccessing files:  52%|█████▏    | 2731/5252 [07:03<05:57,  7.06it/s]


proccessing files:  52%|█████▏    | 2732/5252 [07:03<07:01,  5.98it/s]


proccessing files:  52%|█████▏    | 2733/5252 [07:0

proccessing files:  56%|█████▌    | 2931/5252 [07:34<05:26,  7.11it/s]


proccessing files:  56%|█████▌    | 2932/5252 [07:34<05:03,  7.64it/s]


proccessing files:  56%|█████▌    | 2933/5252 [07:35<05:07,  7.55it/s]


proccessing files:  56%|█████▌    | 2934/5252 [07:35<04:49,  8.01it/s]


proccessing files:  56%|█████▌    | 2935/5252 [07:35<05:19,  7.26it/s]


proccessing files:  56%|█████▌    | 2936/5252 [07:35<06:09,  6.27it/s]


proccessing files:  56%|█████▌    | 2937/5252 [07:35<06:56,  5.56it/s]


proccessing files:  56%|█████▌    | 2938/5252 [07:36<07:14,  5.33it/s]


proccessing files:  56%|█████▌    | 2939/5252 [07:36<06:31,  5.91it/s]


proccessing files:  56%|█████▌    | 2940/5252 [07:36<07:04,  5.45it/s]


proccessing files:  56%|█████▌    | 2941/5252 [07:36<06:10,  6.24it/s]


proccessing files:  56%|█████▌    | 2942/5252 [07:36<06:38,  5.80it/s]


proccessing files:  56%|█████▌    | 2943/5252 [07:36<07:07,  5.41it/s]


proccessing files:  56%|█████▌    | 2944/5252 [07:3

proccessing files:  60%|█████▉    | 3137/5252 [08:06<05:03,  6.96it/s]


proccessing files:  60%|█████▉    | 3138/5252 [08:06<04:48,  7.33it/s]


proccessing files:  60%|█████▉    | 3139/5252 [08:06<04:47,  7.35it/s]


proccessing files:  60%|█████▉    | 3140/5252 [08:06<04:30,  7.80it/s]


proccessing files:  60%|█████▉    | 3141/5252 [08:06<05:41,  6.19it/s]


proccessing files:  60%|█████▉    | 3142/5252 [08:06<06:20,  5.55it/s]


proccessing files:  60%|█████▉    | 3143/5252 [08:07<06:22,  5.51it/s]


proccessing files:  60%|█████▉    | 3144/5252 [08:07<07:08,  4.92it/s]


proccessing files:  60%|█████▉    | 3145/5252 [08:07<06:14,  5.63it/s]


proccessing files:  60%|█████▉    | 3146/5252 [08:07<05:51,  6.00it/s]


proccessing files:  60%|█████▉    | 3147/5252 [08:07<06:23,  5.48it/s]


proccessing files:  60%|█████▉    | 3148/5252 [08:08<06:26,  5.44it/s]


proccessing files:  60%|█████▉    | 3149/5252 [08:08<06:49,  5.14it/s]


proccessing files:  60%|█████▉    | 3150/5252 [08:0

proccessing files:  64%|██████▎   | 3345/5252 [08:39<05:22,  5.91it/s]


proccessing files:  64%|██████▎   | 3346/5252 [08:39<06:08,  5.17it/s]


proccessing files:  64%|██████▎   | 3347/5252 [08:39<05:17,  6.00it/s]


proccessing files:  64%|██████▎   | 3348/5252 [08:39<04:40,  6.78it/s]


proccessing files:  64%|██████▍   | 3349/5252 [08:39<05:00,  6.33it/s]


proccessing files:  64%|██████▍   | 3350/5252 [08:39<05:01,  6.31it/s]


proccessing files:  64%|██████▍   | 3351/5252 [08:40<05:40,  5.58it/s]


proccessing files:  64%|██████▍   | 3352/5252 [08:40<04:58,  6.37it/s]


proccessing files:  64%|██████▍   | 3353/5252 [08:40<04:41,  6.76it/s]


proccessing files:  64%|██████▍   | 3354/5252 [08:40<04:15,  7.43it/s]


proccessing files:  64%|██████▍   | 3355/5252 [08:40<03:58,  7.94it/s]


proccessing files:  64%|██████▍   | 3356/5252 [08:40<03:57,  7.99it/s]


proccessing files:  64%|██████▍   | 3357/5252 [08:40<04:28,  7.06it/s]


proccessing files:  64%|██████▍   | 3358/5252 [08:4

proccessing files:  68%|██████▊   | 3552/5252 [09:11<04:18,  6.57it/s]


proccessing files:  68%|██████▊   | 3553/5252 [09:11<04:07,  6.86it/s]


proccessing files:  68%|██████▊   | 3555/5252 [09:11<03:46,  7.50it/s]


proccessing files:  68%|██████▊   | 3556/5252 [09:11<03:30,  8.06it/s]


proccessing files:  68%|██████▊   | 3557/5252 [09:11<03:30,  8.04it/s]


proccessing files:  68%|██████▊   | 3558/5252 [09:11<03:22,  8.36it/s]


proccessing files:  68%|██████▊   | 3559/5252 [09:11<03:15,  8.65it/s]


proccessing files:  68%|██████▊   | 3560/5252 [09:12<03:23,  8.33it/s]


proccessing files:  68%|██████▊   | 3561/5252 [09:12<04:10,  6.76it/s]


proccessing files:  68%|██████▊   | 3562/5252 [09:12<03:55,  7.19it/s]


proccessing files:  68%|██████▊   | 3563/5252 [09:12<03:47,  7.43it/s]


proccessing files:  68%|██████▊   | 3564/5252 [09:12<03:43,  7.56it/s]


proccessing files:  68%|██████▊   | 3565/5252 [09:12<03:36,  7.79it/s]


proccessing files:  68%|██████▊   | 3566/5252 [09:1

proccessing files:  72%|███████▏  | 3760/5252 [09:42<03:09,  7.86it/s]


proccessing files:  72%|███████▏  | 3761/5252 [09:42<02:57,  8.38it/s]


proccessing files:  72%|███████▏  | 3762/5252 [09:43<03:58,  6.25it/s]


proccessing files:  72%|███████▏  | 3763/5252 [09:43<04:33,  5.45it/s]


proccessing files:  72%|███████▏  | 3764/5252 [09:43<04:02,  6.15it/s]


proccessing files:  72%|███████▏  | 3765/5252 [09:43<03:43,  6.66it/s]


proccessing files:  72%|███████▏  | 3766/5252 [09:43<03:23,  7.28it/s]


proccessing files:  72%|███████▏  | 3767/5252 [09:43<03:44,  6.62it/s]


proccessing files:  72%|███████▏  | 3768/5252 [09:44<03:30,  7.06it/s]


proccessing files:  72%|███████▏  | 3769/5252 [09:44<03:23,  7.30it/s]


proccessing files:  72%|███████▏  | 3770/5252 [09:44<03:10,  7.78it/s]


proccessing files:  72%|███████▏  | 3771/5252 [09:44<03:45,  6.56it/s]


proccessing files:  72%|███████▏  | 3772/5252 [09:44<03:35,  6.87it/s]


proccessing files:  72%|███████▏  | 3773/5252 [09:4

proccessing files:  76%|███████▌  | 3966/5252 [10:15<02:57,  7.25it/s]


proccessing files:  76%|███████▌  | 3967/5252 [10:15<03:08,  6.83it/s]


proccessing files:  76%|███████▌  | 3968/5252 [10:16<03:01,  7.08it/s]


proccessing files:  76%|███████▌  | 3969/5252 [10:16<03:44,  5.71it/s]


proccessing files:  76%|███████▌  | 3970/5252 [10:16<03:18,  6.46it/s]


proccessing files:  76%|███████▌  | 3971/5252 [10:16<03:38,  5.86it/s]


proccessing files:  76%|███████▌  | 3972/5252 [10:16<03:52,  5.49it/s]


proccessing files:  76%|███████▌  | 3973/5252 [10:17<03:47,  5.63it/s]


proccessing files:  76%|███████▌  | 3974/5252 [10:17<03:24,  6.25it/s]


proccessing files:  76%|███████▌  | 3975/5252 [10:17<03:11,  6.66it/s]


proccessing files:  76%|███████▌  | 3976/5252 [10:17<03:37,  5.87it/s]


proccessing files:  76%|███████▌  | 3977/5252 [10:17<03:53,  5.47it/s]


proccessing files:  76%|███████▌  | 3978/5252 [10:18<04:31,  4.70it/s]


proccessing files:  76%|███████▌  | 3979/5252 [10:1

proccessing files:  79%|███████▉  | 4173/5252 [10:49<03:31,  5.10it/s]


proccessing files:  79%|███████▉  | 4175/5252 [10:49<03:00,  5.98it/s]


proccessing files:  80%|███████▉  | 4176/5252 [10:49<02:48,  6.38it/s]


proccessing files:  80%|███████▉  | 4177/5252 [10:49<02:37,  6.83it/s]


proccessing files:  80%|███████▉  | 4178/5252 [10:49<02:28,  7.22it/s]


proccessing files:  80%|███████▉  | 4179/5252 [10:49<02:56,  6.09it/s]


proccessing files:  80%|███████▉  | 4180/5252 [10:50<03:05,  5.79it/s]


proccessing files:  80%|███████▉  | 4181/5252 [10:50<02:42,  6.58it/s]


proccessing files:  80%|███████▉  | 4182/5252 [10:50<02:57,  6.04it/s]


proccessing files:  80%|███████▉  | 4183/5252 [10:50<02:36,  6.81it/s]


proccessing files:  80%|███████▉  | 4184/5252 [10:50<02:26,  7.29it/s]


proccessing files:  80%|███████▉  | 4185/5252 [10:50<02:17,  7.75it/s]


proccessing files:  80%|███████▉  | 4186/5252 [10:51<03:01,  5.86it/s]


proccessing files:  80%|███████▉  | 4187/5252 [10:5

proccessing files:  83%|████████▎ | 4384/5252 [11:21<01:59,  7.25it/s]


proccessing files:  83%|████████▎ | 4385/5252 [11:21<02:15,  6.38it/s]


proccessing files:  84%|████████▎ | 4386/5252 [11:21<02:27,  5.86it/s]


proccessing files:  84%|████████▎ | 4387/5252 [11:22<02:16,  6.32it/s]


proccessing files:  84%|████████▎ | 4388/5252 [11:22<02:35,  5.57it/s]


proccessing files:  84%|████████▎ | 4389/5252 [11:22<02:44,  5.25it/s]


proccessing files:  84%|████████▎ | 4390/5252 [11:22<02:53,  4.96it/s]


proccessing files:  84%|████████▎ | 4391/5252 [11:22<02:28,  5.79it/s]


proccessing files:  84%|████████▎ | 4392/5252 [11:23<02:16,  6.28it/s]


proccessing files:  84%|████████▎ | 4393/5252 [11:23<02:07,  6.75it/s]


proccessing files:  84%|████████▎ | 4394/5252 [11:23<02:16,  6.27it/s]


proccessing files:  84%|████████▎ | 4395/5252 [11:23<02:24,  5.93it/s]


proccessing files:  84%|████████▎ | 4396/5252 [11:23<02:08,  6.64it/s]


proccessing files:  84%|████████▎ | 4397/5252 [11:2

proccessing files:  87%|████████▋ | 4591/5252 [11:54<01:29,  7.43it/s]


proccessing files:  87%|████████▋ | 4592/5252 [11:54<01:38,  6.72it/s]


proccessing files:  87%|████████▋ | 4593/5252 [11:54<01:51,  5.91it/s]


proccessing files:  87%|████████▋ | 4594/5252 [11:54<01:38,  6.68it/s]


proccessing files:  87%|████████▋ | 4595/5252 [11:54<01:42,  6.39it/s]


proccessing files:  88%|████████▊ | 4596/5252 [11:55<01:45,  6.23it/s]


proccessing files:  88%|████████▊ | 4597/5252 [11:55<01:50,  5.92it/s]


proccessing files:  88%|████████▊ | 4598/5252 [11:55<02:04,  5.26it/s]


proccessing files:  88%|████████▊ | 4599/5252 [11:55<01:51,  5.86it/s]


proccessing files:  88%|████████▊ | 4600/5252 [11:55<01:41,  6.40it/s]


proccessing files:  88%|████████▊ | 4601/5252 [11:55<01:33,  6.96it/s]


proccessing files:  88%|████████▊ | 4602/5252 [11:56<01:41,  6.41it/s]


proccessing files:  88%|████████▊ | 4603/5252 [11:56<01:34,  6.84it/s]


proccessing files:  88%|████████▊ | 4604/5252 [11:5

proccessing files:  91%|█████████▏| 4804/5252 [12:27<01:29,  5.03it/s]


proccessing files:  91%|█████████▏| 4805/5252 [12:27<01:17,  5.79it/s]


proccessing files:  92%|█████████▏| 4806/5252 [12:27<01:08,  6.50it/s]


proccessing files:  92%|█████████▏| 4807/5252 [12:27<01:11,  6.22it/s]


proccessing files:  92%|█████████▏| 4808/5252 [12:27<01:17,  5.73it/s]


proccessing files:  92%|█████████▏| 4809/5252 [12:28<01:09,  6.36it/s]


proccessing files:  92%|█████████▏| 4810/5252 [12:28<01:22,  5.36it/s]


proccessing files:  92%|█████████▏| 4811/5252 [12:28<01:13,  5.99it/s]


proccessing files:  92%|█████████▏| 4812/5252 [12:28<01:08,  6.38it/s]


proccessing files:  92%|█████████▏| 4813/5252 [12:28<01:03,  6.91it/s]


proccessing files:  92%|█████████▏| 4814/5252 [12:28<00:59,  7.41it/s]


proccessing files:  92%|█████████▏| 4815/5252 [12:28<00:56,  7.80it/s]


proccessing files:  92%|█████████▏| 4816/5252 [12:29<01:20,  5.39it/s]


proccessing files:  92%|█████████▏| 4817/5252 [12:2

proccessing files:  95%|█████████▌| 5005/5252 [13:05<00:44,  5.57it/s]


proccessing files:  95%|█████████▌| 5006/5252 [13:05<00:38,  6.31it/s]


proccessing files:  95%|█████████▌| 5007/5252 [13:05<00:34,  7.03it/s]


proccessing files:  95%|█████████▌| 5008/5252 [13:05<00:40,  6.02it/s]


proccessing files:  95%|█████████▌| 5009/5252 [13:05<00:44,  5.48it/s]


proccessing files:  95%|█████████▌| 5010/5252 [13:05<00:39,  6.17it/s]


proccessing files:  95%|█████████▌| 5011/5252 [13:06<00:43,  5.51it/s]


proccessing files:  95%|█████████▌| 5012/5252 [13:06<00:46,  5.21it/s]


proccessing files:  95%|█████████▌| 5013/5252 [13:06<00:40,  5.92it/s]


proccessing files:  95%|█████████▌| 5014/5252 [13:06<00:36,  6.46it/s]


proccessing files:  95%|█████████▌| 5015/5252 [13:06<00:44,  5.37it/s]


proccessing files:  96%|█████████▌| 5016/5252 [13:07<00:43,  5.44it/s]


proccessing files:  96%|█████████▌| 5017/5252 [13:07<00:42,  5.49it/s]


proccessing files:  96%|█████████▌| 5018/5252 [13:0

proccessing files:  99%|█████████▉| 5209/5252 [13:48<00:06,  6.44it/s]


proccessing files:  99%|█████████▉| 5210/5252 [13:48<00:07,  5.74it/s]


proccessing files:  99%|█████████▉| 5211/5252 [13:48<00:06,  6.55it/s]


proccessing files:  99%|█████████▉| 5212/5252 [13:48<00:07,  5.71it/s]


proccessing files:  99%|█████████▉| 5213/5252 [13:48<00:06,  6.27it/s]


proccessing files:  99%|█████████▉| 5214/5252 [13:49<00:06,  5.70it/s]


proccessing files:  99%|█████████▉| 5215/5252 [13:49<00:05,  6.25it/s]


proccessing files:  99%|█████████▉| 5216/5252 [13:49<00:05,  6.77it/s]


proccessing files:  99%|█████████▉| 5217/5252 [13:49<00:04,  7.20it/s]


proccessing files:  99%|█████████▉| 5218/5252 [13:49<00:04,  7.38it/s]


proccessing files:  99%|█████████▉| 5219/5252 [13:49<00:05,  6.42it/s]


proccessing files:  99%|█████████▉| 5220/5252 [13:49<00:05,  6.09it/s]


proccessing files:  99%|█████████▉| 5221/5252 [13:50<00:05,  6.04it/s]


proccessing files:  99%|█████████▉| 5222/5252 [13:5

['tonnetz_feats/y.joblib']

In [75]:
X

[array([-0.00508347,  0.01652065, -0.01909658,  0.00093374,  0.01148738,
         0.01229086]),
 array([0.00776046, 0.00182586, 0.01696461, 0.08774168, 0.00090846,
        0.00399765]),
 array([-0.01638275,  0.00857235,  0.00319591,  0.01099057,  0.00664746,
         0.0065252 ]),
 array([-0.00866688,  0.01282036,  0.01369107,  0.06675968,  0.00582066,
         0.00680829]),
 array([-0.00993399,  0.01039659, -0.02107251, -0.03872656,  0.0034335 ,
         0.0084636 ]),
 array([-0.00550932,  0.02240987, -0.05395958,  0.01905941, -0.01009144,
        -0.0017162 ]),
 array([ 0.00050626, -0.00509877, -0.00315197, -0.01337794,  0.00194075,
         0.00357421]),
 array([ 0.00322496,  0.0070189 ,  0.01624741,  0.02483445, -0.00878007,
         0.00720504]),
 array([ 0.00466482,  0.00115378, -0.03825501,  0.02993711, -0.00611291,
         0.00175424]),
 array([-0.01594771,  0.01785636,  0.00055812,  0.02536857,  0.00330571,
         0.0144833 ]),
 array([ 0.00084416,  0.00599511, -0.04541777,